<a href="https://colab.research.google.com/github/thevaibhavpal6/campusx/blob/main/pandas01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
country=['India','pakistan','USA','Nepal','srilanka']

In [7]:
print(type(country))

<class 'list'>

In [9]:
pd.Series(country)

0       India
1    pakistan
2         USA
3       Nepal
4    srilanka
dtype: object

In [10]:
runs=[13,24,56,78,100]

In [11]:
runs

[13, 24, 56, 78, 100]

In [12]:
runs_ser= pd.Series(runs)

In [13]:
runs_ser

0     13
1     24
2     56
3     78
4    100
dtype: int64

In [14]:
marks=[67,57,89,100]

In [15]:
subjects=['maths','english','science','hindi']

In [19]:
pd.Series(marks,index=subjects)

maths       67
english     57
science     89
hindi      100
dtype: int64

In [21]:
marks_series=pd.Series(marks,index=subjects,name='nitish ke marks')

In [22]:
marks_series.name

'nitish ke marks'

In [23]:
marks_series.size

4

In [24]:
marks_series.dtype

dtype('int64')

In [25]:
marks_series

maths       67
english     57
science     89
hindi      100
Name: nitish ke marks, dtype: int64

In [26]:
marks_series.is_unique

True

In [28]:
runs_ser.index

RangeIndex(start=0, stop=5, step=1)

In [33]:
subs = pd.read_csv('/content/subs.csv')

In [31]:
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [39]:
vk=pd.read_csv('/content/kohli_ipl.csv',index_col='match_no')

In [43]:
vk.index.count()

AttributeError: 'Index' object has no attribute 'count'